# Generated by Django 4.2.7 on 2025-06-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MusicAnalysis",
        ),
    ]
