# Generated by Django 4.2.7 on 2025-06-24 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("player", "0002_remove_music_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaybackPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.FloatField(default=0.0)),
                ("last_played_at", models.DateTimeField(auto_now=True)),
                (
                    "music_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player.musicfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "music_file")},
            },
        ),
    ]
